"use client";

/* ─── QualityIndex — Feature Showcase ────────────────────────────────────
   Inspirado en Linear, Apple y Stripe:
   - Stats bar con números clave
   - Secciones alternadas izquierda/derecha (no listas planas)
   - Mockups CSS que simulan el producto real
   - Mucho espacio, headlines grandes, sin "muros de texto"
─────────────────────────────────────────────────────────────────────────── */

type Copy = {
  stats: { stat: string; label: string; sub: string }[];
  features: { eyebrow: string; headline: string; sub: string; bullets: string[] }[];
  itineraryMockup: { dayLabel: string; dayTitle: string; activities: { name: string; tag: string }[]; footerStats: string[] };
  mapMockup: { title: string; routeLabels: string[]; walkTime: string };
  hackMockup: { title: string; tips: { tip: string; save: string }[] };
  toolsTitle: string;
  tools: { icon: string; label: string }[];
  ctaLine1: string;
  ctaLine2: string;
  ctaButton: string;
  ctaSubtext: string;
};

const T: Record<string, Copy> = {
  es: {
    stats: [
      { stat: "100%", label: "Gratis", sub: "Sin tarjeta ni registro" },
      { stat: "30s", label: "Para generarlo", sub: "vs. 8 hs investigando solo" },
      { stat: "6", label: "Idiomas", sub: "Tu itinerario en el tuyo" },
      { stat: "IA +", label: "Expertos", sub: "No es ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Itinerario", headline: "Cada día, pensado para no perder tiempo.", sub: "Actividades ordenadas por zona geográfica, con fotos reales, duración estimada y tips de quienes ya estuvieron ahí.", bullets: ["Fotos reales de cada atracción", "Must-sees marcados con horario y precio", "Tips que no están en Wikipedia"] },
      { eyebrow: "🗺️ Mapa interactivo", headline: "Todos tus puntos. Sin abrir otra app.", sub: "El mapa interactivo muestra cada lugar del itinerario con tiempos a pie y en transporte entre cada uno.", bullets: ["Rutas optimizadas entre actividades", "Tiempos reales de traslado", "Sin necesidad de Google Maps extra"] },
      { eyebrow: "💡 Travel Hacks", headline: "Los trucos que solo da quien ya estuvo.", sub: "Consejos específicos para tu destino generados por IA con criterio de experto: cómo ahorrar, qué evitar, dónde comer bien.", bullets: ["Específicos para tu destino y fechas", "Ahorro real en entradas y transporte", "Restaurantes locales sin trampa turística"] },
    ],
    itineraryMockup: { dayLabel: "DÍA", dayTitle: "Centro Histórico y Arte", activities: [{ name: "Museo del Prado", tag: "⭐ Imperdible" }, { name: "Plaza Mayor", tag: "📸 Foto" }, { name: "Parque del Retiro", tag: "🌿 Relax" }], footerStats: ["⏱ ~6 hs", "💰 ~€35", "🚶 2.1 km"] },
    mapMockup: { title: "🗺️ Mapa del viaje", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Comprá el Abono Turístico de metro — ilimitado por días.", save: "Ahorrás €12" }, { tip: "El Prado los domingos cierra a las 19hs — entrá gratis de 17 a 19.", save: "Gratis" }, { tip: "El menú del día incluye 3 pasos + bebida por €12 en La Latina.", save: "Mejor precio" }] },
    toolsTitle: "🔧 También incluye",
    tools: [{ icon: "✈️", label: "Comparador de vuelos" }, { icon: "🏥", label: "Centros médicos" }, { icon: "🚗", label: "Alquiler de autos" }, { icon: "🛡️", label: "Seguros de viaje" }, { icon: "🚐", label: "Traslados al aeropuerto" }, { icon: "🚨", label: "Botón SOS emergencias" }],
    ctaLine1: "Todo esto, gratis.",
    ctaLine2: "En 30 segundos.",
    ctaButton: "✈️ Generá tu itinerario",
    ctaSubtext: "Sin registro. Sin tarjeta de crédito.",
  },
  en: {
    stats: [
      { stat: "100%", label: "Free", sub: "No card or sign-up" },
      { stat: "30s", label: "To generate it", sub: "vs. 8 hrs researching alone" },
      { stat: "6", label: "Languages", sub: "Your itinerary in yours" },
      { stat: "AI +", label: "Experts", sub: "Not ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Itinerary", headline: "Every day, planned so you never waste time.", sub: "Activities ordered by geographic area, with real photos, estimated duration, and tips from people who've actually been there.", bullets: ["Real photos of every attraction", "Must-sees marked with time and price", "Tips you won't find on Wikipedia"] },
      { eyebrow: "🗺️ Interactive map", headline: "All your stops. No extra app needed.", sub: "The interactive map shows every place in the itinerary with walking and transit times between each one.", bullets: ["Optimized routes between activities", "Real transfer times", "No need for a separate Google Maps"] },
      { eyebrow: "💡 Travel Hacks", headline: "The tricks only someone who's been there can give you.", sub: "Destination-specific tips generated by AI with expert judgment: how to save, what to avoid, where to eat well.", bullets: ["Specific to your destination and dates", "Real savings on tickets and transport", "Local restaurants, no tourist traps"] },
    ],
    itineraryMockup: { dayLabel: "DAY", dayTitle: "Historic Center & Art", activities: [{ name: "Prado Museum", tag: "⭐ Must-see" }, { name: "Plaza Mayor", tag: "📸 Photo" }, { name: "Retiro Park", tag: "🌿 Relax" }], footerStats: ["⏱ ~6 hrs", "💰 ~€35", "🚶 2.1 km"] },
    mapMockup: { title: "🗺️ Trip map", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Get the metro Tourist Pass — unlimited rides for however many days you need.", save: "Save €12" }, { tip: "The Prado closes at 7pm on Sundays — free entry from 5 to 7pm.", save: "Free" }, { tip: "The fixed lunch menu includes 3 courses + a drink for €12 in La Latina.", save: "Best value" }] },
    toolsTitle: "🔧 Also included",
    tools: [{ icon: "✈️", label: "Flight comparison" }, { icon: "🏥", label: "Medical centers" }, { icon: "🚗", label: "Car rental" }, { icon: "🛡️", label: "Travel insurance" }, { icon: "🚐", label: "Airport transfers" }, { icon: "🚨", label: "SOS emergency button" }],
    ctaLine1: "All of this, free.",
    ctaLine2: "In 30 seconds.",
    ctaButton: "✈️ Build my itinerary",
    ctaSubtext: "No sign-up. No credit card.",
  },
  fr: {
    stats: [
      { stat: "100%", label: "Gratuit", sub: "Sans carte ni inscription" },
      { stat: "30s", label: "Pour le générer", sub: "contre 8h de recherche seul" },
      { stat: "6", label: "Langues", sub: "Votre itinéraire dans la vôtre" },
      { stat: "IA +", label: "Experts", sub: "Pas ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Itinéraire", headline: "Chaque jour, pensé pour ne pas perdre de temps.", sub: "Activités classées par zone géographique, avec de vraies photos, une durée estimée et des conseils de ceux qui y sont déjà allés.", bullets: ["Vraies photos de chaque attraction", "Incontournables avec horaire et prix", "Astuces qu'on ne trouve pas sur Wikipédia"] },
      { eyebrow: "🗺️ Carte interactive", headline: "Tous vos points. Sans ouvrir une autre appli.", sub: "La carte interactive affiche chaque lieu de l'itinéraire avec les temps de marche et de transport entre chacun.", bullets: ["Itinéraires optimisés entre les activités", "Temps de trajet réels", "Pas besoin d'une appli Maps supplémentaire"] },
      { eyebrow: "💡 Travel Hacks", headline: "Les astuces que seul quelqu'un qui y est allé peut donner.", sub: "Conseils spécifiques à votre destination générés par IA avec un regard d'expert : comment économiser, quoi éviter, où bien manger.", bullets: ["Spécifiques à votre destination et vos dates", "Économies réelles sur les billets et transports", "Restaurants locaux, sans piège à touristes"] },
    ],
    itineraryMockup: { dayLabel: "JOUR", dayTitle: "Centre historique et art", activities: [{ name: "Musée du Prado", tag: "⭐ Incontournable" }, { name: "Plaza Mayor", tag: "📸 Photo" }, { name: "Parc du Retiro", tag: "🌿 Détente" }], footerStats: ["⏱ ~6 h", "💰 ~35 €", "🚶 2,1 km"] },
    mapMockup: { title: "🗺️ Carte du voyage", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Prenez l'Abono Turístico du métro — trajets illimités pour le nombre de jours voulu.", save: "Économisez 12 €" }, { tip: "Le Prado ferme à 19h le dimanche — entrée gratuite de 17h à 19h.", save: "Gratuit" }, { tip: "Le menu du jour inclut 3 plats + une boisson pour 12 € à La Latina.", save: "Meilleur rapport qualité-prix" }] },
    toolsTitle: "🔧 Aussi inclus",
    tools: [{ icon: "✈️", label: "Comparateur de vols" }, { icon: "🏥", label: "Centres médicaux" }, { icon: "🚗", label: "Location de voiture" }, { icon: "🛡️", label: "Assurance voyage" }, { icon: "🚐", label: "Transferts aéroport" }, { icon: "🚨", label: "Bouton SOS d'urgence" }],
    ctaLine1: "Tout ça, gratuit.",
    ctaLine2: "En 30 secondes.",
    ctaButton: "✈️ Générer mon itinéraire",
    ctaSubtext: "Sans inscription. Sans carte bancaire.",
  },
  it: {
    stats: [
      { stat: "100%", label: "Gratis", sub: "Senza carta né registrazione" },
      { stat: "30s", label: "Per generarlo", sub: "contro 8 ore di ricerca da solo" },
      { stat: "6", label: "Lingue", sub: "Il tuo itinerario nella tua lingua" },
      { stat: "IA +", label: "Esperti", sub: "Non è ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Itinerario", headline: "Ogni giorno, pensato per non perdere tempo.", sub: "Attività ordinate per zona geografica, con foto reali, durata stimata e consigli di chi c'è già stato.", bullets: ["Foto reali di ogni attrazione", "Imperdibili segnati con orario e prezzo", "Consigli che non trovi su Wikipedia"] },
      { eyebrow: "🗺️ Mappa interattiva", headline: "Tutti i tuoi punti. Senza aprire un'altra app.", sub: "La mappa interattiva mostra ogni luogo dell'itinerario con i tempi a piedi e con i mezzi tra uno e l'altro.", bullets: ["Percorsi ottimizzati tra le attività", "Tempi di spostamento reali", "Non serve un'altra app di mappe"] },
      { eyebrow: "💡 Travel Hacks", headline: "I trucchi che solo chi c'è già stato può darti.", sub: "Consigli specifici per la tua destinazione generati dall'IA con criterio esperto: come risparmiare, cosa evitare, dove mangiare bene.", bullets: ["Specifici per la tua destinazione e le tue date", "Risparmio reale su biglietti e trasporti", "Ristoranti locali, senza trappole per turisti"] },
    ],
    itineraryMockup: { dayLabel: "GIORNO", dayTitle: "Centro storico e arte", activities: [{ name: "Museo del Prado", tag: "⭐ Imperdibile" }, { name: "Plaza Mayor", tag: "📸 Foto" }, { name: "Parco del Retiro", tag: "🌿 Relax" }], footerStats: ["⏱ ~6 h", "💰 ~35 €", "🚶 2,1 km"] },
    mapMockup: { title: "🗺️ Mappa del viaggio", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Prendi l'Abono Turístico della metro — corse illimitate per i giorni che ti servono.", save: "Risparmi 12 €" }, { tip: "Il Prado la domenica chiude alle 19 — ingresso gratuito dalle 17 alle 19.", save: "Gratis" }, { tip: "Il menù del giorno include 3 portate + bevanda a 12 € a La Latina.", save: "Miglior rapporto qualità-prezzo" }] },
    toolsTitle: "🔧 Include anche",
    tools: [{ icon: "✈️", label: "Comparatore di voli" }, { icon: "🏥", label: "Centri medici" }, { icon: "🚗", label: "Noleggio auto" }, { icon: "🛡️", label: "Assicurazione di viaggio" }, { icon: "🚐", label: "Trasferimenti aeroportuali" }, { icon: "🚨", label: "Pulsante SOS emergenze" }],
    ctaLine1: "Tutto questo, gratis.",
    ctaLine2: "In 30 secondi.",
    ctaButton: "✈️ Genera il mio itinerario",
    ctaSubtext: "Senza registrazione. Senza carta di credito.",
  },
  de: {
    stats: [
      { stat: "100%", label: "Kostenlos", sub: "Ohne Karte oder Anmeldung" },
      { stat: "30s", label: "Zum Erstellen", sub: "statt 8 Std. allein recherchieren" },
      { stat: "6", label: "Sprachen", sub: "Dein Reiseplan in deiner Sprache" },
      { stat: "KI +", label: "Experten", sub: "Kein ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Reiseplan", headline: "Jeder Tag durchdacht, damit du keine Zeit verlierst.", sub: "Aktivitäten nach geografischer Zone geordnet, mit echten Fotos, geschätzter Dauer und Tipps von Leuten, die schon dort waren.", bullets: ["Echte Fotos jeder Sehenswürdigkeit", "Highlights mit Uhrzeit und Preis markiert", "Tipps, die du nicht bei Wikipedia findest"] },
      { eyebrow: "🗺️ Interaktive Karte", headline: "Alle deine Stationen. Ohne eine weitere App.", sub: "Die interaktive Karte zeigt jeden Ort im Reiseplan mit Geh- und Fahrzeiten zwischen den Stationen.", bullets: ["Optimierte Routen zwischen den Aktivitäten", "Echte Fahrzeiten", "Keine separate Google-Maps-App nötig"] },
      { eyebrow: "💡 Travel Hacks", headline: "Die Tricks, die nur jemand geben kann, der schon dort war.", sub: "Von KI generierte, reisezielspezifische Tipps mit Expertenwissen: wie man spart, was man vermeidet, wo man gut isst.", bullets: ["Spezifisch für dein Reiseziel und deine Daten", "Echte Ersparnis bei Tickets und Transport", "Lokale Restaurants, keine Touristenfallen"] },
    ],
    itineraryMockup: { dayLabel: "TAG", dayTitle: "Historisches Zentrum & Kunst", activities: [{ name: "Prado-Museum", tag: "⭐ Muss man sehen" }, { name: "Plaza Mayor", tag: "📸 Foto" }, { name: "Retiro-Park", tag: "🌿 Entspannung" }], footerStats: ["⏱ ~6 Std", "💰 ~35 €", "🚶 2,1 km"] },
    mapMockup: { title: "🗺️ Reisekarte", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 Min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Hol dir die Metro-Touristenkarte — unbegrenzte Fahrten für so viele Tage, wie du brauchst.", save: "Spare 12 €" }, { tip: "Der Prado schließt sonntags um 19 Uhr — freier Eintritt von 17 bis 19 Uhr.", save: "Kostenlos" }, { tip: "Das Tagesmenü umfasst 3 Gänge + Getränk für 12 € in La Latina.", save: "Bestes Preis-Leistungs-Verhältnis" }] },
    toolsTitle: "🔧 Außerdem enthalten",
    tools: [{ icon: "✈️", label: "Flugvergleich" }, { icon: "🏥", label: "Ärztliche Zentren" }, { icon: "🚗", label: "Mietwagen" }, { icon: "🛡️", label: "Reiseversicherung" }, { icon: "🚐", label: "Flughafentransfers" }, { icon: "🚨", label: "SOS-Notfallknopf" }],
    ctaLine1: "Das alles, kostenlos.",
    ctaLine2: "In 30 Sekunden.",
    ctaButton: "✈️ Meinen Reiseplan erstellen",
    ctaSubtext: "Keine Anmeldung. Keine Kreditkarte.",
  },
  pt: {
    stats: [
      { stat: "100%", label: "Grátis", sub: "Sem cartão nem cadastro" },
      { stat: "30s", label: "Para gerar", sub: "vs. 8h pesquisando sozinho" },
      { stat: "6", label: "Idiomas", sub: "Seu roteiro no seu idioma" },
      { stat: "IA +", label: "Especialistas", sub: "Não é ChatGPT" },
    ],
    features: [
      { eyebrow: "📅 Roteiro", headline: "Cada dia pensado para você não perder tempo.", sub: "Atividades organizadas por zona geográfica, com fotos reais, duração estimada e dicas de quem já esteve lá.", bullets: ["Fotos reais de cada atração", "Imperdíveis marcados com horário e preço", "Dicas que não estão na Wikipédia"] },
      { eyebrow: "🗺️ Mapa interativo", headline: "Todos os seus pontos. Sem abrir outro app.", sub: "O mapa interativo mostra cada lugar do roteiro com tempos a pé e de transporte entre cada um.", bullets: ["Rotas otimizadas entre atividades", "Tempos reais de deslocamento", "Sem precisar de outro app de mapas"] },
      { eyebrow: "💡 Travel Hacks", headline: "Os truques que só quem já esteve lá pode dar.", sub: "Dicas específicas para o seu destino geradas por IA com critério de especialista: como economizar, o que evitar, onde comer bem.", bullets: ["Específicas para seu destino e datas", "Economia real em ingressos e transporte", "Restaurantes locais, sem armadilha turística"] },
    ],
    itineraryMockup: { dayLabel: "DIA", dayTitle: "Centro Histórico e Arte", activities: [{ name: "Museu do Prado", tag: "⭐ Imperdível" }, { name: "Plaza Mayor", tag: "📸 Foto" }, { name: "Parque do Retiro", tag: "🌿 Relaxar" }], footerStats: ["⏱ ~6 h", "💰 ~€35", "🚶 2,1 km"] },
    mapMockup: { title: "🗺️ Mapa da viagem", routeLabels: ["A → Prado", "B → Retiro", "C → Cibeles", "D → Sol"], walkTime: "12 min" },
    hackMockup: { title: "🧠 Travel Hacks · Madrid", tips: [{ tip: "Compre o Abono Turístico do metrô — viagens ilimitadas pelos dias que precisar.", save: "Economize €12" }, { tip: "O Prado fecha às 19h aos domingos — entrada grátis das 17h às 19h.", save: "Grátis" }, { tip: "O menu do dia inclui 3 pratos + bebida por €12 em La Latina.", save: "Melhor custo-benefício" }] },
    toolsTitle: "🔧 Também incluído",
    tools: [{ icon: "✈️", label: "Comparador de voos" }, { icon: "🏥", label: "Centros médicos" }, { icon: "🚗", label: "Aluguel de carros" }, { icon: "🛡️", label: "Seguro viagem" }, { icon: "🚐", label: "Traslados do aeroporto" }, { icon: "🚨", label: "Botão SOS de emergência" }],
    ctaLine1: "Tudo isso, grátis.",
    ctaLine2: "Em 30 segundos.",
    ctaButton: "✈️ Gerar meu roteiro",
    ctaSubtext: "Sem cadastro. Sem cartão de crédito.",
  },
};

/* Mockup: tarjeta de día del itinerario */
function ItineraryMockup({ t }: { t: Copy }) {
  const m = t.itineraryMockup;
  return (
    <div style={{
      background: "white", borderRadius: "16px",
      overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
      width: "100%", maxWidth: "340px",
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    }}>
      {/* Day header */}
      <div style={{ background: "linear-gradient(135deg, #1a2a6c, #2563eb)", padding: "14px 18px", display: "flex", alignItems: "center", gap: "12px" }}>
        <div style={{ background: "rgba(255,255,255,0.15)", borderRadius: "8px", padding: "4px 10px", textAlign: "center" }}>
          <div style={{ fontSize: "8px", color: "rgba(255,255,255,0.7)", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.1em" }}>{m.dayLabel}</div>
          <div style={{ fontSize: "22px", color: "white", fontWeight: 900, lineHeight: 1 }}>1</div>
        </div>
        <div style={{ fontFamily: "'Playfair Display', serif", fontSize: "14px", color: "white", fontWeight: 700 }}>
          {m.dayTitle}
        </div>
      </div>
      {/* Activities */}
      {[
        { time: "09:00", name: m.activities[0].name, tag: m.activities[0].tag, color: "#fef3c7", tagColor: "#92400e" },
        { time: "12:30", name: m.activities[1].name, tag: m.activities[1].tag, color: "#eff6ff", tagColor: "#1e40af" },
        { time: "15:00", name: m.activities[2].name, tag: m.activities[2].tag, color: "#f0fdf4", tagColor: "#166534" },
      ].map((a, i) => (
        <div key={i} style={{ padding: "10px 16px", borderBottom: "1px solid #f3f4f6", display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{ width: "36px", height: "36px", borderRadius: "10px", background: "#f1f5f9", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "11px", fontWeight: 800, color: "#1a2a6c", flexShrink: 0 }}>
            {a.time.split(":")[0]}
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: "12px", fontWeight: 700, color: "#111827", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{a.name}</div>
          </div>
          <span style={{ fontSize: "9px", fontWeight: 700, background: a.color, color: a.tagColor, borderRadius: "999px", padding: "2px 7px", whiteSpace: "nowrap" }}>{a.tag}</span>
        </div>
      ))}
      <div style={{ padding: "10px 16px", background: "#f9fafb", display: "flex", gap: "8px" }}>
        {m.footerStats.map(s => (
          <span key={s} style={{ fontSize: "10px", color: "#6b7280", fontWeight: 600 }}>{s}</span>
        ))}
      </div>
    </div>
  );
}

/* Mockup: mapa con puntos conectados */
function MapMockup({ t }: { t: Copy }) {
  const m = t.mapMockup;
  const points = [
    { x: 60, y: 40, label: "A" },
    { x: 155, y: 90, label: "B" },
    { x: 110, y: 160, label: "C" },
    { x: 230, y: 130, label: "D" },
  ];
  return (
    <div style={{
      background: "#0f172a", borderRadius: "16px",
      overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
      width: "100%", maxWidth: "340px", padding: "20px",
    }}>
      <div style={{ fontSize: "11px", fontWeight: 800, color: "#2ab5a0", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: "12px", fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
        {m.title}
      </div>
      <svg viewBox="0 0 300 210" style={{ width: "100%", borderRadius: "10px", background: "#1e293b" }}>
        {/* Grid lines */}
        {[40,80,120,160,200].map(y => (
          <line key={y} x1="0" y1={y} x2="300" y2={y} stroke="rgba(255,255,255,0.05)" strokeWidth="1" />
        ))}
        {[60,120,180,240].map(x => (
          <line key={x} x1={x} y1="0" x2={x} y2="210" stroke="rgba(255,255,255,0.05)" strokeWidth="1" />
        ))}
        {/* Route line */}
        <polyline
          points={points.map(p => `${p.x + 20},${p.y + 20}`).join(" ")}
          fill="none" stroke="#2ab5a0" strokeWidth="2" strokeDasharray="5,4" opacity="0.7"
        />
        {/* Points */}
        {points.map((p, i) => (
          <g key={i}>
            <circle cx={p.x + 20} cy={p.y + 20} r="12" fill="#1a2a6c" stroke="#2ab5a0" strokeWidth="2" />
            <text x={p.x + 20} y={p.y + 25} textAnchor="middle" fill="white" fontSize="10" fontWeight="bold" fontFamily="sans-serif">{p.label}</text>
          </g>
        ))}
        {/* Walking times */}
        {points.slice(0,-1).map((p, i) => {
          const next = points[i+1];
          const mx = (p.x + next.x)/2 + 20;
          const my = (p.y + next.y)/2 + 14;
          return (
            <text key={i} x={mx} y={my} textAnchor="middle" fill="#2ab5a0" fontSize="8" fontFamily="sans-serif">{m.walkTime}</text>
          );
        })}
      </svg>
      <div style={{ display: "flex", gap: "8px", marginTop: "10px", flexWrap: "wrap" }}>
        {m.routeLabels.map(l => (
          <span key={l} style={{ fontSize: "10px", color: "rgba(255,255,255,0.5)", fontFamily: "'Plus Jakarta Sans', sans-serif" }}>{l}</span>
        ))}
      </div>
    </div>
  );
}

/* Mockup: travel hack card */
function HackMockup({ t }: { t: Copy }) {
  const m = t.hackMockup;
  return (
    <div style={{
      background: "rgba(8,16,54,0.95)", borderRadius: "16px",
      border: "1px solid rgba(42,181,160,0.2)",
      boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
      width: "100%", maxWidth: "340px", padding: "20px",
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    }}>
      <div style={{ fontSize: "11px", fontWeight: 800, color: "#2ab5a0", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: "16px" }}>
        {m.title}
      </div>
      {[
        { icon: "🎟️", tip: m.tips[0].tip, save: m.tips[0].save },
        { icon: "🕗", tip: m.tips[1].tip, save: m.tips[1].save },
        { icon: "🍽️", tip: m.tips[2].tip, save: m.tips[2].save },
      ].map((h, i) => (
        <div key={i} style={{ display: "flex", gap: "10px", marginBottom: i < 2 ? "12px" : 0, paddingBottom: i < 2 ? "12px" : 0, borderBottom: i < 2 ? "1px solid rgba(255,255,255,0.07)" : "none" }}>
          <span style={{ fontSize: "18px", flexShrink: 0 }}>{h.icon}</span>
          <div style={{ flex: 1 }}>
            <p style={{ fontSize: "11px", color: "rgba(255,255,255,0.75)", margin: "0 0 3px 0", lineHeight: 1.4 }}>{h.tip}</p>
            <span style={{ fontSize: "9px", fontWeight: 700, color: "#2ab5a0", background: "rgba(42,181,160,0.12)", borderRadius: "999px", padding: "2px 7px", border: "1px solid rgba(42,181,160,0.2)" }}>
              {h.save}
            </span>
          </div>
        </div>
      ))}
    </div>
  );
}

interface Props {
  language?: string;
}

export function QualityIndex({ language = "es" }: Props) {
  const t = T[language] || T.es;

  const FEATURES = t.features.map((f, i) => ({
    ...f,
    mockup: i === 0 ? <ItineraryMockup t={t} /> : i === 1 ? <MapMockup t={t} /> : <HackMockup t={t} />,
    reverse: i === 1,
  }));

  return (
    <div style={{ marginTop: "48px", fontFamily: "'Plus Jakarta Sans', sans-serif" }}>

      {/* ── Stats bar ── */}
      <div style={{
        display: "flex", gap: "0",
        background: "rgba(8,16,54,0.88)",
        border: "1px solid rgba(255,255,255,0.1)",
        borderRadius: "20px",
        overflow: "hidden",
        marginBottom: "4px",
      }}>
        {t.stats.map((item, i, arr) => (
          <div key={item.label} className="quality-stat-item" style={{
            flex: 1, padding: "18px 16px", textAlign: "center",
            borderRight: i < arr.length - 1 ? "1px solid rgba(255,255,255,0.08)" : "none",
          }}>
            <div style={{ fontSize: "clamp(18px, 2.5vw, 26px)", fontWeight: 900, color: "#2ab5a0", lineHeight: 1, marginBottom: "3px" }}>
              {item.stat}
            </div>
            <div className="quality-stat-label" style={{ fontSize: "11px", fontWeight: 700, color: "white", marginBottom: "2px" }}>{item.label}</div>
            <div style={{ fontSize: "10px", color: "rgba(255,255,255,0.38)", display: "none" }}>{item.sub}</div>
          </div>
        ))}
      </div>

      {/* ── Feature rows ── */}
      <div style={{
        background: "rgba(8,16,54,0.88)",
        border: "1px solid rgba(255,255,255,0.1)",
        borderRadius: "20px",
        overflow: "hidden",
        marginTop: "4px",
      }}>
        {FEATURES.map((feat, i) => (
          <div key={feat.eyebrow}>
            <div className="quality-feature-row" style={{
              display: "flex",
              flexDirection: feat.reverse ? "row-reverse" : "row",
              flexWrap: "wrap",
              alignItems: "center",
              gap: "0",
              padding: "48px 40px",
            }}>
              {/* Text side */}
              <div style={{ flex: "1 1 280px", display: "flex", flexDirection: "column", gap: "16px", padding: "0 24px" }}>
                <p style={{
                  fontSize: "10px", fontWeight: 800, color: "#2ab5a0",
                  textTransform: "uppercase", letterSpacing: "0.16em", margin: 0,
                }}>
                  {feat.eyebrow}
                </p>
                <h3 style={{
                  fontFamily: "'Playfair Display', serif",
                  fontSize: "clamp(1.3rem, 2.5vw, 1.9rem)",
                  fontWeight: 700, color: "white",
                  margin: 0, lineHeight: 1.2,
                }}>
                  {feat.headline}
                </h3>
                <p style={{
                  fontSize: "14px", color: "rgba(255,255,255,0.55)",
                  margin: 0, lineHeight: 1.65,
                }}>
                  {feat.sub}
                </p>
                <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginTop: "4px" }}>
                  {feat.bullets.map(b => (
                    <div key={b} style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <div style={{ width: "16px", height: "16px", borderRadius: "50%", background: "rgba(42,181,160,0.2)", border: "1px solid rgba(42,181,160,0.4)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                        <div style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#2ab5a0" }} />
                      </div>
                      <span style={{ fontSize: "13px", color: "rgba(255,255,255,0.7)", fontWeight: 500 }}>{b}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Mockup side — oculto en mobile, visible en desktop */}
              <div className="quality-mockup-side" style={{
                flex: "1 1 280px",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                padding: "12px 24px",
              }}>
                {feat.mockup}
              </div>
            </div>

            {i < FEATURES.length - 1 && (
              <div style={{ height: "1px", background: "rgba(255,255,255,0.06)", margin: "0 40px" }} />
            )}
          </div>
        ))}

        {/* ── Bottom: herramientas + CTA ── */}
        <div style={{ height: "1px", background: "rgba(255,255,255,0.06)" }} />
        <div className="quality-bottom-row" style={{ padding: "40px 40px 40px", display: "flex", flexWrap: "wrap", gap: "32px", alignItems: "center" }}>
          {/* Tools grid */}
          <div style={{ flex: "1 1 300px" }}>
            <p style={{ fontSize: "10px", fontWeight: 800, color: "#2ab5a0", textTransform: "uppercase", letterSpacing: "0.16em", margin: "0 0 16px 0" }}>
              {t.toolsTitle}
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
              {t.tools.map(tool => (
                <div key={tool.label} style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                  <span style={{ fontSize: "14px" }}>{tool.icon}</span>
                  <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.6)", fontWeight: 500 }}>{tool.label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* CTA */}
          <div style={{ flex: "0 1 260px", display: "flex", flexDirection: "column", gap: "12px", alignItems: "flex-start" }}>
            <p style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.2rem", fontWeight: 700, color: "white", margin: 0, lineHeight: 1.3 }}>
              {t.ctaLine1}<br />{t.ctaLine2}
            </p>
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
              className="quality-cta-btn"
              style={{
                display: "inline-flex", alignItems: "center", gap: "8px",
                background: "linear-gradient(135deg, #2ab5a0, #1a9985)",
                color: "white", border: "none", borderRadius: "12px",
                padding: "12px 24px", fontSize: "13px", fontWeight: 700,
                cursor: "pointer",
                boxShadow: "0 4px 20px rgba(42,181,160,0.35)",
              }}
            >
              {t.ctaButton}
            </button>
            <p style={{ fontSize: "11px", color: "rgba(255,255,255,0.35)", margin: 0 }}>
              {t.ctaSubtext}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
