// AUTO-GENERATED by scripts/build-itinerary-places.mts — do not hand-edit.
// Places are keyed by destination slug -> day number -> array of named places
// that were successfully resolved to coordinates AND matched to a confident
// real photo (Wikipedia-first, OpenStreetMap Nominatim as fallback geocoder;
// see src/lib/imageSearch.ts for the matching/scoring logic). Places with no
// confident match were dropped silently rather than shown with wrong/missing
// photos.
//
// Written incrementally (checkpointed after every day) by the build script
// so an interrupted run can resume instead of restarting from zero.

export interface ItineraryPlace {
  name: string;
  lat: number;
  lon: number;
  imageUrl: string | null;
}

export const itineraryPlaces: Record<string, Record<number, ItineraryPlace[]>> = {
  "paris": {
    "1": [
      {
        "name": "Museo del Louvre",
        "lat": 48.86111111,
        "lon": 2.33583333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/960px-Louvre_Museum_Wikimedia_Commons.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Jardín de las Tullerías",
        "lat": 48.8635662,
        "lon": 2.3269552,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Grande_Roue_de_Paris_-_Louvre_et_Jardins_des_Tuileries.jpg/960px-Grande_Roue_de_Paris_-_Louvre_et_Jardins_des_Tuileries.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Campos Elíseos y Arco de Triunfo",
        "lat": 48.87378,
        "lon": 2.29504,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/960px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Torre Eiffel — primer turno",
        "lat": 48.858296,
        "lon": 2.294479,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/960px-Eiffelturm.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Trocadéro y vistas panorámicas",
        "lat": 48.86083333,
        "lon": 2.29,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Trocadero_and_cemetery.jpg/960px-Trocadero_and_cemetery.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Musée d'Orsay",
        "lat": 48.86055556,
        "lon": 2.32555556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Gare_d%27Orsay_-_Les_Quais.JPG/960px-Gare_d%27Orsay_-_Les_Quais.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Espectáculo de luces de la Torre Eiffel",
        "lat": 48.858296,
        "lon": 2.294479,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/960px-Eiffelturm.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Basílica del Sacré-Cœur",
        "lat": 48.88665,
        "lon": 2.34295,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Sacre_Coeur_1.JPG/960px-Sacre_Coeur_1.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Place du Tertre",
        "lat": 48.88653889,
        "lon": 2.34077222,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Paris_Montmartre_Place_du_Tertre_dsc07247.jpg/960px-Paris_Montmartre_Place_du_Tertre_dsc07247.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Canal Saint-Martin",
        "lat": 48.8689561,
        "lon": 2.3671691,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/89_Alfred_Sisley%2C_Le_Canal_Saint_Martin%2C_1872.jpg/960px-89_Alfred_Sisley%2C_Le_Canal_Saint_Martin%2C_1872.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Barrio Latino y la Sorbona",
        "lat": 48.85,
        "lon": 2.3425,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/P1300734_Paris_V_place_de_la_Sorbonne_rwk.jpg/960px-P1300734_Paris_V_place_de_la_Sorbonne_rwk.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Catedral de Notre-Dame (exterior)",
        "lat": 48.853,
        "lon": 2.3498,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Notre-Dame_de_Paris_2013-07-24.jpg/960px-Notre-Dame_de_Paris_2013-07-24.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Jardín de Luxemburgo",
        "lat": 48.848611,
        "lon": 2.334028,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Expo_Louis-Comfort_Tiffany.JPG/960px-Expo_Louis-Comfort_Tiffany.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "5": [
      {
        "name": "Palacio de Versalles",
        "lat": 48.80472222,
        "lon": 2.12027778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_083.jpg/960px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_083.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Jardines de Versalles",
        "lat": 48.80805556,
        "lon": 2.10833333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Vue_a%C3%A9rienne_du_domaine_de_Versailles_le_20_ao%C3%BBt_2014_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_22.jpg/960px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_le_20_ao%C3%BBt_2014_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_22.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Trianón — palacetes privados de la corte",
        "lat": 48.882839,
        "lon": 2.343059,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Le_Trianon%2C_80_boulevard_de_Rochechouart%2C_Paris_18e.jpg/960px-Le_Trianon%2C_80_boulevard_de_Rochechouart%2C_Paris_18e.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "nueva-york": {
    "1": [
      {
        "name": "Central Park al amanecer",
        "lat": 40.7825,
        "lon": -73.96611111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Manhattan02_ST_07_crop.JPG/960px-Manhattan02_ST_07_crop.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Upper West Side y Columbus Circle",
        "lat": 40.76674,
        "lon": -73.98142,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Museum_of_Arts_and_Design_%28MAD%29_-_NYC_%2851395616531%29.jpg/960px-Museum_of_Arts_and_Design_%28MAD%29_-_NYC_%2851395616531%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Times Square",
        "lat": 40.7581,
        "lon": -73.9858,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Times_Square_closed_due_to_bomb_scare.jpg/960px-Times_Square_closed_due_to_bomb_scare.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Brooklyn Bridge al amanecer",
        "lat": 40.7062175,
        "lon": -73.9970208,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/LOC_Brooklyn_Bridge_and_East_River_7.png/960px-LOC_Brooklyn_Bridge_and_East_River_7.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "DUMBO — Down Under the Manhattan Bridge Overpass",
        "lat": 40.70305556,
        "lon": -73.98944444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/23/Fulton_FerryDUMBO_Pictures014.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Brooklyn Heights Promenade",
        "lat": 40.6973713,
        "lon": -73.9973894,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Brooklyn_Heights_Townhouses.jpg/960px-Brooklyn_Heights_Townhouses.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Williamsburg: brunch y cultura",
        "lat": 40.714622,
        "lon": -73.95345,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Knickerbocker_north.jpg/960px-Knickerbocker_north.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "9/11 Memorial & Museum",
        "lat": 40.71138889,
        "lon": -74.01361111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/9-11_Memorial_and_Museum_%2828815276064%29.jpg/960px-9-11_Memorial_and_Museum_%2828815276064%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Staten Island Ferry",
        "lat": 40.6424267,
        "lon": -74.0745595,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Staten_island_ferry_verrazano.jpg/960px-Staten_island_ferry_verrazano.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Wall Street y el Charging Bull",
        "lat": 40.70476,
        "lon": -74.00597,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f0/120_Wall_Street_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "One World Observatory",
        "lat": 40.712949,
        "lon": -74.0130438,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Wtc7_jan06.jpg/960px-Wtc7_jan06.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "MoMA — Museum of Modern Art",
        "lat": 40.76166667,
        "lon": -73.9775,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/MoMa_NY_USA_1.jpg/960px-MoMa_NY_USA_1.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "High Line",
        "lat": 40.7483,
        "lon": -74.005,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/High_Line_20th_Street_looking_downtown.jpg/960px-High_Line_20th_Street_looking_downtown.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Chelsea Market",
        "lat": 40.7420513,
        "lon": -74.0048973,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Chelsea_Market_%2849052085186%29.jpg/960px-Chelsea_Market_%2849052085186%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Empire State Building de noche",
        "lat": 40.74861111,
        "lon": -73.98555556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Bomber_Crashed_into_Empire_State_Building_1945.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "5": [
      {
        "name": "Apollo Theater",
        "lat": 40.8100895,
        "lon": -73.9499948,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Harlem_-_Apollo_Theater_%2848555309512%29.jpg/960px-Harlem_-_Apollo_Theater_%2848555309512%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "roma": {
    "1": [
      {
        "name": "Circo Máximo",
        "lat": 38.91980556,
        "lon": -6.33230556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/VR_Merida_03-Circo_Romano.jpg/960px-VR_Merida_03-Circo_Romano.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Museos Vaticanos y Capilla Sixtina",
        "lat": 41.90305556,
        "lon": 12.45444444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/82/Sistina-interno.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Basílica de San Pedro",
        "lat": 41.90222222,
        "lon": 12.45341667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Saint_Peter%27s_Basilica_facade%2C_Rome%2C_Italy.jpg/960px-Saint_Peter%27s_Basilica_facade%2C_Rome%2C_Italy.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Castel Sant'Angelo",
        "lat": 41.9031178,
        "lon": 12.4663427,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Castillo_y_puente_Sant%27Angelo%2C_Roma%2C_Italia%2C_2022-09-16%2C_DD_11.jpg/960px-Castillo_y_puente_Sant%27Angelo%2C_Roma%2C_Italia%2C_2022-09-16%2C_DD_11.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Prati — el barrio del Vaticano",
        "lat": 41.908078,
        "lon": 12.465706,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Palace_Justice%281%29.jpg/960px-Palace_Justice%281%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Trastevere — el barrio más romano de Roma",
        "lat": 41.889444,
        "lon": 12.469722,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Roma_-_Basilica_di_Santa_Maria_in_Trastevere_20231228-02.jpg/960px-Roma_-_Basilica_di_Santa_Maria_in_Trastevere_20231228-02.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Campo de' Fiori",
        "lat": 41.89566378,
        "lon": 12.47204654,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Il_Valle_delle_Rose_....JPG/960px-Il_Valle_delle_Rose_....JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Piazza Navona",
        "lat": 41.8989282,
        "lon": 12.4731178,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Fontana_del_Nettuno_3.jpg/960px-Fontana_del_Nettuno_3.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Panthéon",
        "lat": 41.898616,
        "lon": 12.4768334,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Obelisk_and_fountaine_of_the_Pantheon.jpg/960px-Obelisk_and_fountaine_of_the_Pantheon.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Fontana di Trevi al amanecer",
        "lat": 41.9007,
        "lon": 12.4839,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Trevi_-_SS_Vincenzo_e_Anastasio.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Escalinata Española",
        "lat": 41.9060703,
        "lon": 12.4828718,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Scalinata_della_Trinit%C3%A0_dei_Monti.jpg/960px-Scalinata_della_Trinit%C3%A0_dei_Monti.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Villa Borghese — el pulmón de Roma",
        "lat": 41.91416667,
        "lon": 12.49222222,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Villa_Borghese_-_entrata_2669.JPG/960px-Villa_Borghese_-_entrata_2669.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "5": [
      {
        "name": "Aventino y el hueco de los caballeros",
        "lat": 41.8836945,
        "lon": 12.4794173,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Sant%27Anselmo_Sculpture_in_Rome.jpg/960px-Sant%27Anselmo_Sculpture_in_Rome.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Testaccio — el barrio de la comida romana",
        "lat": 41.87611111,
        "lon": 12.475,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Porta_San_Paolo_-_Piramid_Cestius.JPG/960px-Porta_San_Paolo_-_Piramid_Cestius.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Palatino y los jardines Farnesio",
        "lat": 41.889167,
        "lon": 12.479444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Sunset_of_Ponte_Palatino.jpg/960px-Sunset_of_Ponte_Palatino.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "cancun": {
    "1": [
      {
        "name": "Mercado 28 — el Cancún real",
        "lat": 21.161,
        "lon": -86.834,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Mercado_28%2C_Canc%C3%BAn_2014.jpg/960px-Mercado_28%2C_Canc%C3%BAn_2014.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Centro de Cancún al anochecer",
        "lat": 21.182051,
        "lon": -86.830544,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Cancun_86.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "2": [
      {
        "name": "Ferry a Isla Mujeres",
        "lat": 21.18055556,
        "lon": -86.75833333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Landsat_Cancun_Mexico_parque.jpg/960px-Landsat_Cancun_Mexico_parque.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Vuelta a Cancún vía Valladolid",
        "lat": 21.16141611,
        "lon": -86.82481111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cancun_Strand_Luftbild_%2822143397586%29.jpg/960px-Cancun_Strand_Luftbild_%2822143397586%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Akumal — nado con tortugas marinas",
        "lat": 20.40093528,
        "lon": -87.32243611,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Akumal_Scuba_Diving_%284317784232%29.jpg/960px-Akumal_Scuba_Diving_%284317784232%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "5": [
      {
        "name": "Quinta Avenida de Playa del Carmen",
        "lat": 20.6281425,
        "lon": -87.0755,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/PlayadelCarmen3.png/960px-PlayadelCarmen3.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Playa de Playa del Carmen",
        "lat": 20.6281425,
        "lon": -87.0755,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/PlayadelCarmen3.png/960px-PlayadelCarmen3.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "barcelona": {
    "1": [
      {
        "name": "Sagrada Familia",
        "lat": 41.403561,
        "lon": 2.174347,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sagrada_Familia_Barcelona_2.jpg/960px-Sagrada_Familia_Barcelona_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Casa Batlló o Casa Milà (La Pedrera)",
        "lat": 41.414455,
        "lon": 2.153567,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Casa-Museo_Gaud%C3%AD%2C_Francesc_Berenguer.jpg/960px-Casa-Museo_Gaud%C3%AD%2C_Francesc_Berenguer.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Park Güell",
        "lat": 41.41361111,
        "lon": 2.15277778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Parc_guell_-_panoramio.jpg/960px-Parc_guell_-_panoramio.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Barrio de Gràcia al atardecer",
        "lat": 41.38277778,
        "lon": 2.17694444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Catedral_de_Barcelona_%289248804702%29.jpg/960px-Catedral_de_Barcelona_%289248804702%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Barri Gòtic — el corazón medieval",
        "lat": 41.3828966,
        "lon": 2.1757919,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Call_de_Barcelona_Marlet.jpg/960px-Call_de_Barcelona_Marlet.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "El Born y el Mercat de Santa Caterina",
        "lat": 41.384232,
        "lon": 2.182438,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Barcelona_Part_Deux_-_69_%283466084959%29.jpg/960px-Barcelona_Part_Deux_-_69_%283466084959%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Barceloneta — la playa urbana de Barcelona",
        "lat": 41.38209,
        "lon": 2.1855154,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Metrobarcelonetal42.jpg/960px-Metrobarcelonetal42.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Puerto Olímpico y la Vila Olímpica",
        "lat": 41.3891832,
        "lon": 2.1985018,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/22_01_21_Port_Ol%C3%ADmpic_0501_RalfR_wp.jpg/960px-22_01_21_Port_Ol%C3%ADmpic_0501_RalfR_wp.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Castillo de Montjuïc al atardecer",
        "lat": 41.3633756,
        "lon": 2.1661443,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Castell_de_Montjuic_-_Fossat_entrada_-_Barcelona_%28Catalonia%29.jpg/960px-Castell_de_Montjuic_-_Fossat_entrada_-_Barcelona_%28Catalonia%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Sant Joan — la caminata de las vistas",
        "lat": 41.40055556,
        "lon": 2.16805556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Passeig_de_Sant_Joan_Barcelona_Catalonia.JPG/960px-Passeig_de_Sant_Joan_Barcelona_Catalonia.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Basílica de Montserrat y la Moreneta",
        "lat": 41.5933945,
        "lon": 1.8380058,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Cremallera_de_Montserrat.JPG/960px-Cremallera_de_Montserrat.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "5": [
      {
        "name": "MNAC — Museo Nacional de Arte de Cataluña",
        "lat": 41.3686024,
        "lon": 2.1534616,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/El_Greco_-_Christ_Carrying_the_Cross_-_Google_Art_Project.jpg/960px-El_Greco_-_Christ_Carrying_the_Cross_-_Google_Art_Project.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Poble Sec — el barrio que come bien",
        "lat": 41.371848,
        "lon": 2.171958,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Mirador_Poble_Sec.JPG/960px-Mirador_Poble_Sec.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Fundació Joan Miró",
        "lat": 39.555,
        "lon": 2.60916667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Miro%27s_Studio_Sert_-_Palma_de_Mallorca.jpg/960px-Miro%27s_Studio_Sert_-_Palma_de_Mallorca.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Bunkers del Carmel — la vista definitiva de Barcelona",
        "lat": 41.4193923,
        "lon": 2.1616974,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Santuari_Carmel1.jpg/960px-Santuari_Carmel1.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "tokio": {
    "1": [
      {
        "name": "Meiji Shrine — santuario en el bosque",
        "lat": 35.6748417,
        "lon": 139.6996266,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Meiji_Shrine_Inner_Garden.JPG/960px-Meiji_Shrine_Inner_Garden.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Shinjuku — el barrio que nunca duerme",
        "lat": 35.68563889,
        "lon": 139.69095,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Shinjuku_Park_Tower_7_Desember_2003_cropped2.jpg/960px-Shinjuku_Park_Tower_7_Desember_2003_cropped2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Shibuya Crossing al amanecer",
        "lat": 35.6594951,
        "lon": 139.7004982,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/ShibuyaEastExit2005-5.jpg/960px-ShibuyaEastExit2005-5.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Omotesando — la avenida de las arquitecturas",
        "lat": 35.66513,
        "lon": 139.71248,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Omotesando_Tokyo_spring_2012.JPG/960px-Omotesando_Tokyo_spring_2012.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Senso-ji al amanecer",
        "lat": 35.71455556,
        "lon": 139.79663889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sensoji_2023.jpg/960px-Sensoji_2023.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Skytree Tokyo",
        "lat": 35.7101474,
        "lon": 139.8107146,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/TokyoSkyTree_Station-Main_Entrance-20120420.jpg/960px-TokyoSkyTree_Station-Main_Entrance-20120420.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Akihabara — el barrio del futuro",
        "lat": 35.69833333,
        "lon": 139.77305556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Akiba_denkigai.jpg/960px-Akiba_denkigai.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Ueno — museos y parque de cerezos",
        "lat": 35.71547,
        "lon": 139.77402,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/af/KaneijiPagoda1270.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "4": [
      {
        "name": "Mercado Exterior de Tsukiji",
        "lat": 35.66138889,
        "lon": 139.76972222,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/2018_Tsukiji_fish_market.jpg/960px-2018_Tsukiji_fish_market.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Ginza — el Champs-Élysées de Tokio",
        "lat": 35.6720135,
        "lon": 139.7647202,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/22/Armani_Ginza_Tower.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "teamLab Borderless o teamLab Planets",
        "lat": 35.6620024,
        "lon": 139.7434178,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/TeamLab_Borderless%2C_Odaiba%2C_Tokyo%2C_Japan_%2849070839652%29.jpg/960px-TeamLab_Borderless%2C_Odaiba%2C_Tokyo%2C_Japan_%2849070839652%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Odaiba — la ciudad artificial en la bahía",
        "lat": 35.63,
        "lon": 139.775,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/2018_FCG_Headquarters_Building_2.jpg/960px-2018_FCG_Headquarters_Building_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "5": [
      {
        "name": "Enoshima — la isla sagrada",
        "lat": 35.29933056,
        "lon": 139.48090833,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/EnoshimaAeralPhoto1988JP14.jpg/960px-EnoshimaAeralPhoto1988JP14.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "londres": {
    "1": [
      {
        "name": "Tower of London",
        "lat": 51.50805556,
        "lon": -0.07611111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Tower_of_London_from_the_Shard_%288515883950%29.jpg/960px-Tower_of_London_from_the_Shard_%288515883950%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Tower Bridge",
        "lat": 51.5055158,
        "lon": -0.0753665,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Tower_Bridge_at_Dawn.jpg/960px-Tower_Bridge_at_Dawn.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Borough Market",
        "lat": 51.50490833,
        "lon": -0.09108889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/52/Borough_market.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "2": [
      {
        "name": "British Museum",
        "lat": 51.5193118,
        "lon": -0.1267051,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/British_Museum_%28aerial%29.jpg/960px-British_Museum_%28aerial%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Covent Garden",
        "lat": 51.5125,
        "lon": -0.1225,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/%E6%9F%AF%E8%8A%AC%E5%9C%92_%2840400019900%29.jpg/960px-%E6%9F%AF%E8%8A%AC%E5%9C%92_%2840400019900%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "National Gallery",
        "lat": 51.508881,
        "lon": -0.1283826,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9f/El_Greco%2C_The_Adoration_of_the_Name_of_Jesus.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "3": [
      {
        "name": "Portobello Road Market",
        "lat": 51.5160858,
        "lon": -0.2051174,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Portobello.market.london.arp.jpg/960px-Portobello.market.london.arp.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Hyde Park y Kensington Gardens",
        "lat": 51.50861111,
        "lon": -0.16361111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/87/Aerial_view_of_Hyde_Park.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Harrods y Knightsbridge",
        "lat": 51.4992104,
        "lon": -0.1629893,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Harrods_%28London%29.jpg/960px-Harrods_%28London%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Palacio de Buckingham y Changing of the Guard",
        "lat": 51.501,
        "lon": -0.142,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg/960px-Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "St James's Park",
        "lat": 51.5031295,
        "lon": -0.133165,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/St._James%27s_Park_2009.jpg/960px-St._James%27s_Park_2009.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Greenwich: Meridiano y Observatorio",
        "lat": 51.483363,
        "lon": -0.006732,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Old_Royal_Naval_College_and_Queen%27s_House%2C_Greenwich_-_2021-10-30.jpg/960px-Old_Royal_Naval_College_and_Queen%27s_House%2C_Greenwich_-_2021-10-30.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "amsterdam": {
    "1": [
      {
        "name": "Rijksmuseum",
        "lat": 52.36,
        "lon": 4.8853,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/South_facade_of_the_Rijksmuseum_Amsterdam_%28DSCF0528%29.jpg/960px-South_facade_of_the_Rijksmuseum_Amsterdam_%28DSCF0528%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Museo Van Gogh",
        "lat": 52.35833333,
        "lon": 4.88111111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Van_Gogh_Museum%2C_Kurokawa_wing.jpg/960px-Van_Gogh_Museum%2C_Kurokawa_wing.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Vondelpark",
        "lat": 52.35694444,
        "lon": 4.86638889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Amsterdam%2C_Vondelpark%2C_at_the_pond-2.jpg/960px-Amsterdam%2C_Vondelpark%2C_at_the_pond-2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Casa de Ana Frank",
        "lat": 52.3751472,
        "lon": 4.8840398,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Amsterdam_%28NL%29%2C_Anne-Frank-Huis_--_2015_--_7185.jpg/960px-Amsterdam_%28NL%29%2C_Anne-Frank-Huis_--_2015_--_7185.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Amsterdam Noord — A'DAM Tower y EYE Film Museum",
        "lat": 52.4052674,
        "lon": 4.9462925,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/33/Amsterdamse_stadsdelen_2010.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Brouwerij 't IJ — cervecería en el molino",
        "lat": 52.36666667,
        "lon": 4.92638889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Brouwerijhetij.jpg/960px-Brouwerijhetij.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "lisboa": {
    "1": [
      {
        "name": "Castillo de São Jorge",
        "lat": 38.71389,
        "lon": -9.13333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/LisbonCastle.jpg/960px-LisbonCastle.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Pastéis de Belém",
        "lat": 38.7,
        "lon": -9.2,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Bel%C3%A9m_%2816650010329%29.jpg/960px-Bel%C3%A9m_%2816650010329%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Monasterio de los Jerónimos",
        "lat": 38.697846,
        "lon": -9.205601,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/1502_legte_K%C3%B6nig_Manuel_I._den_Grundstein_f%C3%BCr_das_Hieronymus_Kloster_in_Lissabon._06.jpg/960px-1502_legte_K%C3%B6nig_Manuel_I._den_Grundstein_f%C3%BCr_das_Hieronymus_Kloster_in_Lissabon._06.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Torre de Belém y Padrão dos Descobrimentos",
        "lat": 38.7,
        "lon": -9.2,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Bel%C3%A9m_%2816650010329%29.jpg/960px-Bel%C3%A9m_%2816650010329%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Barrio Alto al atardecer",
        "lat": 38.71222222,
        "lon": -9.145,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/78/Bairro_Alto_Lisboa_3.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ]
  },
  "dubai": {
    "1": [
      {
        "name": "Dubai Mall y el Acuario",
        "lat": 25.1975,
        "lon": 55.27916667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Dubai_Mall_10.jpg/960px-Dubai_Mall_10.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Burj Khalifa — At the Top",
        "lat": 25.1970336,
        "lon": 55.2741329,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dubai_Fountain_from_At_The_Top_of_Burj_Khalifa.JPG/960px-Dubai_Fountain_from_At_The_Top_of_Burj_Khalifa.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Abra por el Dubai Creek",
        "lat": 25.26444444,
        "lon": 55.31166667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/DubaiCollage.jpg/960px-DubaiCollage.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "JBR Beach y The Beach",
        "lat": 25.0767543,
        "lon": 55.1312746,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dubai_Jumeirah_Beach.JPG/960px-Dubai_Jumeirah_Beach.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "marrakech": {
    "1": [
      {
        "name": "Plaza Jemaa el-Fna por la mañana",
        "lat": 31.62583333,
        "lon": -7.98944444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Djemaa_el_Fna.jpg/960px-Djemaa_el_Fna.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Souks de la medina",
        "lat": 31.6245582,
        "lon": -7.9852794,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Menara_Garden%2CMorocco%2CMarrakech.jpg/960px-Menara_Garden%2CMorocco%2CMarrakech.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Jemaa el-Fna al atardecer — el gran espectáculo",
        "lat": 31.62583333,
        "lon": -7.98944444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Djemaa_el_Fna.jpg/960px-Djemaa_el_Fna.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Palacio de la Bahía",
        "lat": 31.62159167,
        "lon": -7.98223056,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Bahia_Palace_large_court.jpg/960px-Bahia_Palace_large_court.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Jardín Majorelle y Museo Bereber",
        "lat": 31.642788,
        "lon": -8.003141,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/YSL_01_Eingangsportal.jpg/960px-YSL_01_Eingangsportal.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "bangkok": {
    "1": [
      {
        "name": "Gran Palacio y Wat Phra Kaew",
        "lat": 13.75013889,
        "lon": 100.49202778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/0005574-%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%9A%E0%B8%A3%E0%B8%A1%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%B1%E0%B8%87%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%A3%E0%B8%B1%E0%B8%95%E0%B8%99%E0%B8%A3%E0%B8%B2%E0%B8%A8%E0%B8%94%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%A1.jpg/960px-0005574-%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%9A%E0%B8%A3%E0%B8%A1%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%B1%E0%B8%87%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%A3%E0%B8%B1%E0%B8%95%E0%B8%99%E0%B8%A3%E0%B8%B2%E0%B8%A8%E0%B8%94%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%A1.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Wat Pho — el Buda Reclinado",
        "lat": 13.7463456,
        "lon": 100.4927381,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Rangsi_Vadhana_Mausoleum_%E0%B8%A3%E0%B8%B1%E0%B8%87%E0%B8%A9%E0%B8%B5%E0%B8%A7%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B8%B2_%282025%29_-_img_05.jpg/960px-Rangsi_Vadhana_Mausoleum_%E0%B8%A3%E0%B8%B1%E0%B8%87%E0%B8%A9%E0%B8%B5%E0%B8%A7%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B8%B2_%282025%29_-_img_05.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Wat Arun — el Templo del Amanecer",
        "lat": 13.74147222,
        "lon": 100.48608333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AD%E0%B8%A3%E0%B8%B8%E0%B8%93%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%A3%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3_%E0%B8%81%E0%B8%A5%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B8%B7%E0%B8%99.jpg/960px-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AD%E0%B8%A3%E0%B8%B8%E0%B8%93%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%A3%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3_%E0%B8%81%E0%B8%A5%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B8%B7%E0%B8%99.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Mercado Chatuchak",
        "lat": 13.80083333,
        "lon": 100.55138889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chatuchak_weekend_market_roofs.jpg/960px-Chatuchak_weekend_market_roofs.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Terminal 21 — el mall de los aeropuertos temáticos",
        "lat": 13.7375,
        "lon": 100.56055556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Terminal_21_Asok_Bangkok_20202021.jpg/960px-Terminal_21_Asok_Bangkok_20202021.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Wat Benchamabophit — el Templo de Mármol",
        "lat": 13.76658333,
        "lon": 100.51408333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Wat_Benjamabophit1.jpg/960px-Wat_Benjamabophit1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Sky Bar Lebua — el bar más alto del mundo",
        "lat": 13.72111111,
        "lon": 100.5175,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Lebua_at_State_Tower_IMG_1402_01.jpg/960px-Lebua_at_State_Tower_IMG_1402_01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "rio-de-janeiro": {
    "1": [
      {
        "name": "Barrio de Santa Teresa",
        "lat": -22.9175,
        "lon": -43.18805556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/At_Rio_de_Janeiro_2019_521.jpg/960px-At_Rio_de_Janeiro_2019_521.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Playa de Ipanema",
        "lat": -22.9873109,
        "lon": -43.2021257,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ipanema_rio.jpg/960px-Ipanema_rio.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Pan de Azúcar — teleférico",
        "lat": -22.94944444,
        "lon": -43.15666667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/P%C3%A3o_de_A%C3%A7ucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg/960px-P%C3%A3o_de_A%C3%A7ucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Barrio de Urca y almuerzo",
        "lat": -22.9489,
        "lon": -43.1656,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Rio_de_Janeiro_-_P%C3%A3o_de_A%C3%A7ucar_-_Cablecar.jpg/960px-Rio_de_Janeiro_-_P%C3%A3o_de_A%C3%A7ucar_-_Cablecar.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Playa de Copacabana",
        "lat": -22.96703333,
        "lon": -43.18069722,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Copacabana_06_2016_2377.jpg/960px-Copacabana_06_2016_2377.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Samba en el Lapa",
        "lat": -22.914351,
        "lon": -43.181516,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Arcos_da_Lapa_01.jpg/960px-Arcos_da_Lapa_01.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Estadio Maracanã — tour o partido",
        "lat": -22.91222222,
        "lon": -43.23027778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Maracana_2022.jpg/960px-Maracana_2022.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Jardim Botânico",
        "lat": -22.96333333,
        "lon": -43.22222222,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Aleia_Barbosa_Rodrigues%2C_no_Jardim_Bot%C3%A2nico_do_Rio_de_Janeiro_-_Brasil.jpg/960px-Aleia_Barbosa_Rodrigues%2C_no_Jardim_Bot%C3%A2nico_do_Rio_de_Janeiro_-_Brasil.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Lagoa Rodrigo de Freitas y ciclovía",
        "lat": -22.97027778,
        "lon": -43.21055556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/LagoaRodrigoFreitasRJ10092006.jpg/960px-LagoaRodrigoFreitasRJ10092006.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Parque Lage — la mansión entre el bosque",
        "lat": -22.9606,
        "lon": -43.212,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Parque_lage_4_-_Caio_Ara%C3%BAjo_fotografia.jpg/960px-Parque_lage_4_-_Caio_Ara%C3%BAjo_fotografia.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "buenos-aires": {
    "1": [
      {
        "name": "Plaza de Mayo y la Casa Rosada",
        "lat": -35.41666667,
        "lon": -60.16666667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/PLAZA_MITRE_CON_MUNICIPALIDAD_-_panoramio.jpg/960px-PLAZA_MITRE_CON_MUNICIPALIDAD_-_panoramio.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Barrio de San Telmo",
        "lat": -34.62096111,
        "lon": -58.37057778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Iglesia_de_Nuestra_Se%C3%B1ora_de_Bel%C3%A9n_%28San_Telmo%29.JPG/960px-Iglesia_de_Nuestra_Se%C3%B1ora_de_Bel%C3%A9n_%28San_Telmo%29.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "La Boca y el Caminito",
        "lat": -34.6335103,
        "lon": -58.3590424,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Supercl%C3%A1sico_Boca_River_%2816750360624%29.jpg/960px-Supercl%C3%A1sico_Boca_River_%2816750360624%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Puerto Madero — el barrio más nuevo",
        "lat": -34.6103764,
        "lon": -58.3622067,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Buenos_Aires_2.0.jpg/960px-Buenos_Aires_2.0.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Cementerio de la Recoleta",
        "lat": -34.59055556,
        "lon": -58.39055556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Recoleta_montage.jpg/960px-Recoleta_montage.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Feria de Recoleta y Museo Nacional de Bellas Artes",
        "lat": -34.59055556,
        "lon": -58.39055556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Recoleta_montage.jpg/960px-Recoleta_montage.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Avenida Alvear y los palacios belle époque",
        "lat": -34.6006393,
        "lon": -58.370533,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Bifurcaci%C3%B3n.jpg/960px-Bifurcaci%C3%B3n.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Bosques de Palermo y el Rosedal",
        "lat": -34.58888889,
        "lon": -58.43055556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Palermo_montage.jpg/960px-Palermo_montage.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "MALBA — Museo de Arte Latinoamericano",
        "lat": -34.57697222,
        "lon": -58.40338889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Buenos_Aires_-_Palermo_-_Malba.jpg/960px-Buenos_Aires_-_Palermo_-_Malba.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "miami": {
    "1": [
      {
        "name": "Art Deco Historic District — Ocean Drive",
        "lat": 25.785833,
        "lon": -80.134167,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Miami_Beach_FL_Arch_Dist_Collins_Ave_down_south01.jpg/960px-Miami_Beach_FL_Arch_Dist_Collins_Ave_down_south01.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Brickell y el skyline del atardecer",
        "lat": 25.758,
        "lon": -80.193,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Miami_neighborhoodsmap.png/960px-Miami_neighborhoodsmap.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Wynwood Walls",
        "lat": 25.8011377,
        "lon": -80.1953188,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Midtownmiamicenter.jpg/960px-Midtownmiamicenter.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Design District — lujo y arte contemporáneo",
        "lat": 25.78583333,
        "lon": -80.13416667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/SouthBeachMiamiBeach.jpg/960px-SouthBeachMiamiBeach.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Vida nocturna en South Beach",
        "lat": 25.81388889,
        "lon": -80.1325,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Miamimetroarea.jpg/960px-Miamimetroarea.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Coconut Grove — el barrio bohemio",
        "lat": 25.71666667,
        "lon": -80.25,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Coconut_Grove_Street_20100321.jpg/960px-Coconut_Grove_Street_20100321.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "praga": {
    "1": [
      {
        "name": "Castillo de Praga — apertura",
        "lat": 50.09,
        "lon": 14.4,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Karl%C5%AFv_most_Praha%2C_Star%C3%A9_M%C4%9Bsto_20170810_007.jpg/960px-Karl%C5%AFv_most_Praha%2C_Star%C3%A9_M%C4%9Bsto_20170810_007.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Puente de Carlos al atardecer",
        "lat": 40.39503333,
        "lon": -3.70465,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Puente_de_Praga_-_Madrid_R%C3%ADo.JPG/960px-Puente_de_Praga_-_Madrid_R%C3%ADo.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Plaza de la Ciudad Vieja y el Reloj Astronómico",
        "lat": 50.0875,
        "lon": 14.42138889,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Old_Town_Square_-_panorama_2.jpg/960px-Old_Town_Square_-_panorama_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Josefov — el barrio judío",
        "lat": 50.0897547,
        "lon": 14.4180959,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Jewish_tawnhall_%28Prague%29.jpg/960px-Jewish_tawnhall_%28Prague%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Vyšehrad — la otra fortaleza",
        "lat": 50.0642146,
        "lon": 14.4194469,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Vysehrad_as_seen_over_the_Vltava_from_Cisarska_louka_732.jpg/960px-Vysehrad_as_seen_over_the_Vltava_from_Cisarska_louka_732.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Letná Park — el Beer Garden con mejor vista",
        "lat": 50.0964045,
        "lon": 14.4141409,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Praha%2C_Letn%C3%A1%2C_sad.jpg/960px-Praha%2C_Letn%C3%A1%2C_sad.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "lima": {
    "1": [
      {
        "name": "Parque Kennedy y el corazón de Miraflores",
        "lat": -12.1217806,
        "lon": -77.0304221,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Parque_Kennedy_-_Lima%2C_Peru.jpg/960px-Parque_Kennedy_-_Lima%2C_Peru.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Malecón de Miraflores y los acantilados",
        "lat": -12.12091,
        "lon": -77.02893,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Comunal_Coworking%2C_Lima%2C_Peru_%28Unsplash_4YAhiaZkUfs%29.jpg/960px-Comunal_Coworking%2C_Lima%2C_Peru_%28Unsplash_4YAhiaZkUfs%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Plaza Mayor y los Balcones Coloniales",
        "lat": -12.04596,
        "lon": -77.03054,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/You_are_not_allowed_to_follow_me_Into_this_town_square_And_then_run_away.jpg/960px-You_are_not_allowed_to_follow_me_Into_this_town_square_And_then_run_away.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Convento de Santo Domingo y las Catacumbas",
        "lat": -12.04408611,
        "lon": -77.03192778,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Bas%C3%ADlica_y_convento_de_Santo_Domingo_2.jpg/960px-Bas%C3%ADlica_y_convento_de_Santo_Domingo_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Chinatown de Lima — el Barrio Chino",
        "lat": -12.0848,
        "lon": -76.9708,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/ULIMA_2019.jpg/960px-ULIMA_2019.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Museo Larco — el tesoro precolombino",
        "lat": -12.072496,
        "lon": -77.070862,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Lima_museo_larco.jpg/960px-Lima_museo_larco.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "MATE — Museo Mario Testino",
        "lat": -11.7614004,
        "lon": -76.3094366,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/FMIB_49719_San_Mateo.jpeg/960px-FMIB_49719_San_Mateo.jpeg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "florencia": {
    "1": [
      {
        "name": "Catedral de Santa María del Fiore (El Duomo)",
        "lat": 43.77305556,
        "lon": 11.25694444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/View_of_Santa_Maria_del_Fiore_in_Florence.jpg/960px-View_of_Santa_Maria_del_Fiore_in_Florence.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Baptisterio de San Juan",
        "lat": 43.77305556,
        "lon": 11.255,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Firenze_Battistero_di_San_Giovanni_Esterno_04.jpg/960px-Firenze_Battistero_di_San_Giovanni_Esterno_04.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Galleria degli Uffizi",
        "lat": 43.7683129,
        "lon": 11.2558009,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Palazzo_della_camera_di_commercio_a_Firenze%2C_terrazza_panoramica%2C_vista_uffizi%2C_tribuna.jpg/960px-Palazzo_della_camera_di_commercio_a_Firenze%2C_terrazza_panoramica%2C_vista_uffizi%2C_tribuna.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Ponte Vecchio y el Oltrarno",
        "lat": 43.76798889,
        "lon": 11.25319167,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Ponte_Vecchio_%28Florencia%29.jpg/960px-Ponte_Vecchio_%28Florencia%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Galleria dell'Accademia — el David",
        "lat": 43.7769174,
        "lon": 11.2587579,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/David_at_the_Galleria_dell%27Accademia_%2861351%29.jpg/960px-David_at_the_Galleria_dell%27Accademia_%2861351%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "estambul": {
    "1": [
      {
        "name": "Santa Sofía",
        "lat": 41.0085046,
        "lon": 28.9800112,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Hagia_Irene%2C_Istanbul_%2852112279404%29_%28cropped%29.jpg/960px-Hagia_Irene%2C_Istanbul_%2852112279404%29_%28cropped%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Mezquita Azul (Sultanahmet Camii)",
        "lat": 41.0053851,
        "lon": 28.9768247,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Exterior_of_Sultan_Ahmed_I_Mosque_in_Istanbul%2C_Turkey_002.jpg/960px-Exterior_of_Sultan_Ahmed_I_Mosque_in_Istanbul%2C_Turkey_002.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Palacio de Topkapi",
        "lat": 41.0129795,
        "lon": 28.9840659,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Topkap%C4%B1_-_01.jpg/960px-Topkap%C4%B1_-_01.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Cisterna Basílica — el palacio subterráneo",
        "lat": 41.0084795,
        "lon": 28.9783826,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Cisterna_Bas%C3%ADlica%2C_Estambul%2C_Turqu%C3%ADa%2C_2024-09-28%2C_DD_58-60_HDR.jpg/960px-Cisterna_Bas%C3%ADlica%2C_Estambul%2C_Turqu%C3%ADa%2C_2024-09-28%2C_DD_58-60_HDR.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Gran Bazar",
        "lat": 41.01058056,
        "lon": 28.96793333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Istanbul_asv2021-11_img41_Grand_Bazaar.jpg/960px-Istanbul_asv2021-11_img41_Grand_Bazaar.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Bazar de las Especias (Mısır Çarşısı)",
        "lat": 41.01058056,
        "lon": 28.96793333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Istanbul_asv2021-11_img41_Grand_Bazaar.jpg/960px-Istanbul_asv2021-11_img41_Grand_Bazaar.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Palacio de Dolmabahçe",
        "lat": 41.03944444,
        "lon": 29.00166667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Palacio_de_Dolmabah%C3%A7e%2C_Estambul%2C_Turqu%C3%ADa%2C_2024-09-29%2C_DD_24.jpg/960px-Palacio_de_Dolmabah%C3%A7e%2C_Estambul%2C_Turqu%C3%ADa%2C_2024-09-29%2C_DD_24.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Istiklal Caddesi y el Barrio de Beyoğlu",
        "lat": 41.033865,
        "lon": 28.9781765,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Istanbul%2C_%C4%B0stikl%C3%A2l_Caddesi%2C_2023.jpg/960px-Istanbul%2C_%C4%B0stikl%C3%A2l_Caddesi%2C_2023.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Torre de Gálata",
        "lat": 41.02563232,
        "lon": 28.97415319,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Istanbul_asv2020-02_img48_Galata_Tower.jpg/960px-Istanbul_asv2020-02_img48_Galata_Tower.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "ciudad-de-mexico": {
    "1": [
      {
        "name": "Zócalo y la Catedral Metropolitana",
        "lat": 19.43277778,
        "lon": -99.13305556,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Z%C3%B3calo%2C_Ciudad_de_M%C3%A9xico_%2832846556446%29_%28cropped%29.jpg/960px-Z%C3%B3calo%2C_Ciudad_de_M%C3%A9xico_%2832846556446%29_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Templo Mayor — las ruinas aztecas bajo la ciudad",
        "lat": 19.465905,
        "lon": -99.086754,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/29/Mexico_city_temple_night.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Bellas Artes y la Alameda",
        "lat": 19.4353,
        "lon": -99.1414,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bellas_Artes_01.jpg/960px-Bellas_Artes_01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Pirámides de Teotihuacán — primera hora",
        "lat": 19.69265167,
        "lon": -98.84458027,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/15-07-Mexico-Vorauswahl-RalfR-WMA_0159.jpg/960px-15-07-Mexico-Vorauswahl-RalfR-WMA_0159.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Xochimilco — los canales prehispánicos",
        "lat": 19.295466,
        "lon": -99.093157,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Vista_a%C3%A9rea_del_Parque_Ecol%C3%B3gico_de_Xochimilco_01.jpg/960px-Vista_a%C3%A9rea_del_Parque_Ecol%C3%B3gico_de_Xochimilco_01.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Coyoacán — el barrio de Frida Kahlo",
        "lat": 19.3498606,
        "lon": -99.1619751,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Coyoacan_001.jpg/960px-Coyoacan_001.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Mezcal y tacos de autor en la Roma Norte",
        "lat": 19.4406779,
        "lon": -99.1395511,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/MuseumTequilaMezcalGaribaldi_crop.JPG/960px-MuseumTequilaMezcalGaribaldi_crop.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "4": [
      {
        "name": "Museo Nacional de Antropología",
        "lat": 19.42611111,
        "lon": -99.18611111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/94/Musee_National_Anthropologie-Entree.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Bosque de Chapultepec",
        "lat": 19.4126439,
        "lon": -99.2038347,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/La_Feria..jpg/960px-La_Feria..jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Paseo de la Reforma y el Ángel",
        "lat": 19.43308333,
        "lon": -99.15475,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Monumento_a_Col%C3%B3n_Paseo_de_la_Reforma_Ciudad_de_M%C3%A9xico.jpg/960px-Monumento_a_Col%C3%B3n_Paseo_de_la_Reforma_Ciudad_de_M%C3%A9xico.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "singapur": {
    "1": [
      {
        "name": "Gardens by the Bay",
        "lat": 1.2811486,
        "lon": 103.86496,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Supertree_Grove%2C_Gardens_by_the_Bay%2C_Singapore_-_20120712-02.jpg/960px-Supertree_Grove%2C_Gardens_by_the_Bay%2C_Singapore_-_20120712-02.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Museo ArtScience",
        "lat": 1.2861382,
        "lon": 103.8592297,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg/960px-ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Chinatown Heritage Centre",
        "lat": 1.2834963,
        "lon": 103.8443296,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/NE4_DT19_Chinatown_MRT_Exit_A_Pagoda_Street_%28new_signage%29_20220109_130757.jpg/960px-NE4_DT19_Chinatown_MRT_Exit_A_Pagoda_Street_%28new_signage%29_20220109_130757.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Little India — Serangoon Road",
        "lat": 1.3068427,
        "lon": 103.8492736,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Little_India_%284048444495%29.jpg/960px-Little_India_%284048444495%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Clarke Quay y el río Singapur al atardecer",
        "lat": 1.2882413,
        "lon": 103.8464276,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/%28SGP-Singapore%29_Clarke_Quay_MRT_Station_Exit_A_2026-02-17.jpg/960px-%28SGP-Singapore%29_Clarke_Quay_MRT_Station_Exit_A_2026-02-17.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Haw Par Villa — el parque de los diez infiernos",
        "lat": 1.282678,
        "lon": 103.7818016,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/CC25_Haw_Par_Villa_MRT_Platforms_%28new_signage%29_20260408_173730.jpg/960px-CC25_Haw_Par_Villa_MRT_Platforms_%28new_signage%29_20260408_173730.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "medellin": {
    "1": [
      {
        "name": "Plaza Botero y el Museo de Antioquia",
        "lat": 6.246,
        "lon": -75.568,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Edificio_del_Caf%C3%A9-Parque_San_Antonio_2.JPG/960px-Edificio_del_Caf%C3%A9-Parque_San_Antonio_2.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Parque de las Luces y el centro de Medellín",
        "lat": 6.2460451,
        "lon": -75.5723006,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Parque_Pies_Descalzos-Arenal-Medellin.JPG/960px-Parque_Pies_Descalzos-Arenal-Medellin.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Barrio El Poblado — parques y cafés",
        "lat": 6.2008,
        "lon": -75.56362,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/46/El_Poblado-Medellin.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "2": [
      {
        "name": "Parque Arví — el bosque sobre Medellín",
        "lat": 6.26555556,
        "lon": -75.49694444,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e1/MetrocableArv%C3%AD1.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "3": [
      {
        "name": "Jardín Botánico de Medellín",
        "lat": 6.27083333,
        "lon": -75.56416667,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Orchidiarium_-_Medellin_Botanical_Gardens.jpg/960px-Orchidiarium_-_Medellin_Botanical_Gardens.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Mercado del Río",
        "lat": 6.2260794,
        "lon": -75.5754423,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/AFUERAS_DEL_MUSEO_DE_ARTE_MODERNO_MEDELLIN_2016.jpg/960px-AFUERAS_DEL_MUSEO_DE_ARTE_MODERNO_MEDELLIN_2016.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "cusco": {
    "1": [
      {
        "name": "Plaza de Armas de Cusco — llegada y aclimatación",
        "lat": -13.516711,
        "lon": -71.978823,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Plaza_de_Cusco_Allison_Bellido.jpg/960px-Plaza_de_Cusco_Allison_Bellido.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Sacsayhuamán — la fortaleza inca",
        "lat": -13.507778,
        "lon": -71.982222,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Sacsayhuam%C3%A1n%2C_Cusco%2C_Per%C3%BA%2C_2015-07-31%2C_DD_01.JPG/960px-Sacsayhuam%C3%A1n%2C_Cusco%2C_Per%C3%BA%2C_2015-07-31%2C_DD_01.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Mercado de Pisac",
        "lat": -13.4218011,
        "lon": -71.8489681,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Ulrikes_Pisac_Peru.Tonje_Gram.JPG/960px-Ulrikes_Pisac_Peru.Tonje_Gram.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Ollantaytambo — la ciudad inca viviente",
        "lat": -13.2573858,
        "lon": -72.2631311,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Ollantaytambo_2.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      }
    ],
    "3": [
      {
        "name": "Tren a Aguas Calientes (Machu Picchu Pueblo)",
        "lat": -13.154833,
        "lon": -72.525333,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Machu_Picchu%2C_Peru_-_Laslovarga_%28262%29.jpg/960px-Machu_Picchu%2C_Peru_-_Laslovarga_%28262%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Machu Picchu — la ciudadela",
        "lat": -13.174478,
        "lon": -72.541974,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Machu_Picchu_a_p%C5%99%C3%ADjezdov%C3%A1_cesta_-_panoramio.jpg/960px-Machu_Picchu_a_p%C5%99%C3%ADjezdov%C3%A1_cesta_-_panoramio.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Regreso a Cusco",
        "lat": -13.5163,
        "lon": -71.9781,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Catedral%2C_Plaza_de_Armas%2C_Cusco%2C_Per%C3%BA%2C_2015-07-31%2C_DD_73.JPG/960px-Catedral%2C_Plaza_de_Armas%2C_Cusco%2C_Per%C3%BA%2C_2015-07-31%2C_DD_73.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  },
  "viena": {
    "1": [
      {
        "name": "Catedral de San Esteban (Stephansdom)",
        "lat": 48.208427,
        "lon": 16.373256,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Wien_-_Stephansdom.JPG/960px-Wien_-_Stephansdom.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Hofburg — el Palacio Imperial",
        "lat": 48.2063293,
        "lon": 16.3656259,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Wien_-_Neue_Hofburg.JPG/960px-Wien_-_Neue_Hofburg.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "2": [
      {
        "name": "Palacio de Schönbrunn",
        "lat": 48.1849894,
        "lon": 16.3115684,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Sch%C3%B6nbrunn.JPG/960px-Wien_-_Schloss_Sch%C3%B6nbrunn.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Naschmarkt — el mercado más vienés",
        "lat": 48.19888889,
        "lon": 16.36361111,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Naschmarkt_Wien_1900.jpg/960px-Naschmarkt_Wien_1900.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      },
      {
        "name": "Belvedere — El Beso de Klimt",
        "lat": 48.1939172,
        "lon": 16.3804024,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Vienna-_Belvedere_-_52051400437.jpg/960px-Vienna-_Belvedere_-_52051400437.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ],
    "3": [
      {
        "name": "Kunsthistorisches Museum",
        "lat": 48.2037395,
        "lon": 16.3617819,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/04/MuseumsQuartier.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
      },
      {
        "name": "Concierto de música clásica en Viena",
        "lat": 48.200489,
        "lon": 16.372739,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Wien_-_Haus_des_Wiener_Musikvereins_%282%29.JPG/960px-Wien_-_Haus_des_Wiener_Musikvereins_%282%29.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
      }
    ]
  }
};
